NewStaffRoles::
    db "    1998 HOLD     "
    db "     VEJLEDER     "
    db "    INSTRUKTØR    "
    db "  MANUSFORFATTER  "
    db "   PROGRAMMØR     "
    db " FIGURDESIGNER    "
    db "    KOMPONIST     "
    db "     GRAFIK       "
    db "  TEKNISK STØTTE  "
    db "  NORSK VERSION   "
    db "  SÆRLIG TAK TIL  "

DebugStaffRoles::
    db "   FEJLSØGNING    "

OriginalStaffRoles::
    db "    1993 HOLD     "
    db " DUNGEON DESIGNER "
    db "   ILLUSTRATOR    "
    db "    PRODUCENT     "
    db "  LED PRODUSENT   "
    db "                  "

NewStaffPeople::
    db "                  "
    db "  TAKASHI TEZUKA  "
    db "YOSINORI TUTIYAMA "
    db " NOBUO MATSUMIYA  "
    db "    EIJI NOTO     "
    db "   KIYOSHI KODA   "
    db "SIGEHIRO KASAMATU "
    db "  MIKIO MISHIMA   "
    db "   KYOKO KIMURA   "
    db "   YUICHI OZAKI   "
    db "   KEIKO IZAWA    "
    db "   N KOGANEZAWA   "
    db "TOBIAS V LANGHOFF "
    db "JULIUS V LANGHOFF "
    db " AQ KQXGRENASBERG "
    db "  AKIYA SAKAMOTO  "
    db " R&D2 DEBUG HOLD  "
    db " SUPER MARIO KLUB "
    db "YASUHISA YAMAMURA "
    db " KENSUKE TANABE   "
    db "YOSHIAKI KOIZUMI  "
    db " KAZUAKI MORITA   "
    db "TAKAMITSU KUZUHARA"
    db "MASANAO ARIMOTO   "
    db " SHIGEFUMI HINO   "
    db " KAZUMI TOTAKA    "
    db " MINAKO HAMANO    "
    db " KOZUE ISHIKAWA   "
    db " YOUICHI KOTABE   "
    db "KOHOLITION HOLD   "
    db "TOSHIHIKO NAKAGO  "
    db "   KOJI KONDO     "
    db "TOMOAKI KUROUME   "
    db "MASAICHI OKUMURA  "
    db "   KANAE WADA     "
    db "SHIGERU MIYAMOTO  "
    db "HIROSHI YAMAUCHI  "
    db "     SLUT         "